apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dump-pid
spec:
  selector:
    matchLabels:
      component: dump-pid
  template:
    metadata:
      labels:
        component: dump-pid
    spec:
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: ''
      - name: volume
        persistentVolumeClaim:
          claimName: my-azurefile
      containers:
      - command:
        - bash
        - -c
        - |
          apt-get update && apt-get install -y jq psmisc;
          while true;do
          date;ps -e -w -o "thcount,cgname,args,pid"  --no-headers | sort -k 1 -nr | head;
          for i in $(chroot /host crictl pods | grep -v NotReady | tail -n +2| cut -d ' ' -f1);do
          chroot /host crictl inspectp $i | jq '. | "\(.info.pid) \(.status.metadata.name)"';
          PID=$(ps -ef | grep -v grep | grep $(chroot /host crictl inspectp $i | jq '.info.pid')| tr -s ' ' |cut -d ' ' -f3);
          echo MainPID:$PID;pstree $PID;done;echo;
          done > /data/pthreads-$(hostname).log
        image: ubuntu
        name: dump-pid
        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: volume
          mountPath: /data
        securityContext:
          privileged: true
      hostNetwork: true
      hostPID: true
      hostIPC: true
